<!-- YE PAGES KO RESTRICT KAR RAHA HAI, TAKI BINA LOGIN KIYE KOI DIRECT PAGES OPEN NA KAR PAYE ADMINPANEL K -->
<?php
//USE OF SESSION
	$_SESSION['ADMINID'];
//CONDITION AGAR BINA LOGIN KIYE PAGE OPEN KARO	
	if ($_SESSION['ADMINID']=="") {
		echo "<script>window.location='index.php'</script>";
	}
?>